name: home
description: Microfrontend de la p치gina principal del usuario.

publish_to: 'none' # 游댢 No se publica, ser치 orquestado por `chasis`.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  # 游늷 游댃 Manejo de estado con BLoC
  flutter_bloc: ^8.1.3  

  # 游늷 游깴 Navegaci칩n con `go_router`
  go_router: ^10.1.2  

  # 游늷 游니 Cliente HTTP para recibir datos de `chasis`
  dio: ^5.3.2         

  # 游늷 游댏 Almacenamiento seguro del token de autenticaci칩n
  flutter_secure_storage: ^8.0.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
